// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6P2vsyXXVVe4kTm5_hI0PCIZczJJz5w',
    appId: '1:233691880915:android:2b440870eb979a06342326',
    messagingSenderId: '233691880915',
    projectId: 'evently-app-844c5',
    storageBucket: 'evently-app-844c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2F1y0OyZyyhSC7Pl3T2AsxuNORkwCgvg',
    appId: '1:233691880915:ios:024c396632741059342326',
    messagingSenderId: '233691880915',
    projectId: 'evently-app-844c5',
    storageBucket: 'evently-app-844c5.firebasestorage.app',
    iosClientId: '233691880915-o9svogaafd7htfoused7vaop50pn089s.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiHUlE97gAgRA2DTjgEAUrN4Xc5o-Gce4',
    appId: '1:233691880915:web:240a046c4f6857c7342326',
    messagingSenderId: '233691880915',
    projectId: 'evently-app-844c5',
    authDomain: 'evently-app-844c5.firebaseapp.com',
    storageBucket: 'evently-app-844c5.firebasestorage.app',
    measurementId: 'G-39D73XRGBB',
  );

}